### ISSUE TITLE
Game crash on waystone use.

### ISSUE THREAD

**Issue by Aantara** [red2blue/AQM3#6]
Able to replicate consistently. Cannot use waystones without the game crashing immediately upon clicking on the stone.

**Comment by Aantara** [comment]
Update: If you collect and place the waystone, it works fine, no crash. Only seem to crash on newly discovered waystones (like in villages).

**Comment by red2blue** [comment]
Please provide crash logs

**Comment by Aantara** [comment]
[crash-2021-12-27_12.33.13-client.txt](https://github.com/red2blue/AQM3/files/7781739/crash-2021-12-27_12.33.13-client.txt)
[crash-2021-12-27_12.34.37-client.txt](https://github.com/red2blue/AQM3/files/7781740/crash-2021-12-27_12.34.37-client.txt)

**Comment by red2blue** [comment]
should be fixed
